/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [378.22KB] > C:\Users\nbisw\Desktop\My Portfolio\3D Models\ABOUT\scene-transformed.glb [822.21KB] (-117%)
Author: Aartee (https://sketchfab.com/Aartee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-battle-wizard-ffdcd461607d45c580d251d5ab064348
Title: Stylized Battle Wizard
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Armlet_low_WizardMat_0.geometry} material={materials.WizardMat} position={[-36.5, 36.913, -12.824]} rotation={[-1.579, 0.355, -1.574]} scale={100} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
