/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [37.38KB] > C:\Users\nbisw\Desktop\My Portfolio\3D Models\STAFF\scene-transformed.glb [782.4KB] (-1993%)
Author: Rob Jacks (https://sketchfab.com/RobynJacks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/witch-casting-spell-4a8b8672511a40799dff97998ac885f7
Title: witch casting spell
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object002_hair_0.geometry} material={materials.hair} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_skin_0.geometry} material={materials.skin} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_shoes_0.geometry} material={materials.shoes} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_eyes_0.geometry} material={materials.eyes} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_main_1_0.geometry} material={materials.main_1} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_main_2_0.geometry} material={materials.main_2} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_fish_0.geometry} material={materials.fish} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_gem_0.geometry} material={materials.material} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_gen_gaurd_0.geometry} material={materials.gen_gaurd} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_book_back_0.geometry} material={materials.book_back} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_book_page_0.geometry} material={materials.book_page} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_mouth_0.geometry} material={materials.mouth} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_teeth_0.geometry} material={materials.teeth} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
      <mesh geometry={nodes.Object002_water_0.geometry} material={materials.water} position={[-0.034, 0.772, -0.047]} rotation={[0, -0.401, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
