/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aartee (https://sketchfab.com/Aartee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-battle-wizard-ffdcd461607d45c580d251d5ab064348
Title: Stylized Battle Wizard
*/

"use client";

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

const About = React.memo(function About(props) {
  const { nodes, materials } = useGLTF('/models/scene-transformed-about.glb')

  const modelRef = useRef();
  

  useFrame((state) => {
    modelRef.current.position.y =
      -1.7 + Math.sin(state.clock.elapsedTime) * 0.17;

      
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <mesh
        name="Armlet_low_WizardMat_0"
        castShadow
        receiveShadow
        geometry={nodes.Armlet_low_WizardMat_0.geometry}
        material={materials.WizardMat}
        position={[-2.8, -3.37, -25]} // Adjusted Y-axis position closer to original
        rotation={[-1.579, 0.355, -1.574]}
        scale={10} // Smaller scale to avoid being too small
        userData={{ name: 'Armlet_low_WizardMat_0' }}
      />
    </group>
  )
});

export default About;

useGLTF.preload('/models/scene-transformed-about.glb')