/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rob Jacks (https://sketchfab.com/RobynJacks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/witch-casting-spell-4a8b8672511a40799dff97998ac885f7
Title: witch casting spell
*/

"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default React.memo(function HomeModel(props) {
  const { nodes, materials } = useGLTF("/models/scene-transformed_home.glb");

  const modelRef = useRef();
  let rotationSpeed = 0.0015; // Slower speed of rotation
  let rotationDirection = 1; // 1 for left, -1 for right
  const maxRotation = (20 * Math.PI) / 180; // 5 degrees in radians

  useFrame((state) => {
    if (modelRef.current) {
      // Rotate the model left and right
      modelRef.current.rotation.y += rotationSpeed * rotationDirection;

      // Switch direction after exceeding the 5-degree limit
      if (modelRef.current.rotation.y >= maxRotation) {
        rotationDirection = -1; // Switch to right rotation
      } else if (modelRef.current.rotation.y <= -maxRotation) {
        rotationDirection = 1; // Switch to left rotation
      }

      // Floating animation (vertical movement)
      modelRef.current.position.y =
        -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0, -0.05, 0]} // Centered
      scale={[2, 2, 2]} // Larger scale
      rotation={[-0.1, 0, 0]} // Keep rotation as is
    >
      <mesh
        name="Object002_hair_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_hair_0.geometry}
        material={materials.hair}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_hair_0" }}
      />
      <mesh
        name="Object002_skin_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_skin_0.geometry}
        material={materials.skin}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_skin_0" }}
      />
      <mesh
        name="Object002_shoes_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_shoes_0.geometry}
        material={materials.shoes}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_shoes_0" }}
      />
      <mesh
        name="Object002_eyes_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_eyes_0.geometry}
        material={materials.eyes}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_eyes_0" }}
      />
      <mesh
        name="Object002_main_1_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_main_1_0.geometry}
        material={materials.main_1}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_main 1_0" }}
      />
      <mesh
        name="Object002_main_2_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_main_2_0.geometry}
        material={materials.main_2}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_main 2_0" }}
      />
      <mesh
        name="Object002_fish_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_fish_0.geometry}
        material={materials.fish}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_fish_0" }}
      />
      <mesh
        name="Object002_gem_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_gem_0.geometry}
        material={materials.material}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_gem_0" }}
      />
      <mesh
        name="Object002_gen_gaurd_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_gen_gaurd_0.geometry}
        material={materials.gen_gaurd}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_gen gaurd_0" }}
      />
      <mesh
        name="Object002_book_back_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_book_back_0.geometry}
        material={materials.book_back}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_book back_0" }}
      />
      <mesh
        name="Object002_book_page_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_book_page_0.geometry}
        material={materials.book_page}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_book page_0" }}
      />
      <mesh
        name="Object002_mouth_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_mouth_0.geometry}
        material={materials.mouth}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_mouth_0" }}
      />
      <mesh
        name="Object002_teeth_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_teeth_0.geometry}
        material={materials.teeth}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_teeth_0" }}
      />
      <mesh
        name="Object002_water_0"
        castShadow
        receiveShadow
        geometry={nodes.Object002_water_0.geometry}
        material={materials.water}
        position={[-0.034, 0.772, -0.047]}
        rotation={[0, -0.401, 0]}
        scale={0.001}
        userData={{ name: "Object002_water_0" }}
      />
    </group>
  );
});

useGLTF.preload("/models/scene-transformed_home.glb");
